engines:
  duplication:
    enabled: true
checks:
  Similar code:
    enabled: false
languages:
  JavaScript: true
exclude_paths:
  - "spec/*"
  - "src/main/webapp/bower_components/**"
  - enabled.yml
  - disabled.yml
