languages:
  JavaScript: true
exclude_paths:
  - "spec/*"
  - "src/main/webapp/bower_components/**"
  - enabled.yml
  - disabled.yml
engines:
  # ... CONFIG CONTENT ...
  duplication:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      Similar code:
        enabled: false
