---
engines:
  csslint:
    enabled: true
    checks:
        box-sizing:
          enabled: false
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
    checks:
      Similar code:
        enabled: false
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.coffee"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- spec/*
- src/main/webapp/bower_components/**/*
- enabled.yml
- disabled.yml
