version: '2'
services:
    rentit-app:
        image: rentit
        external_links:
            - rentit-mysql:mysql
            - rentit-elasticsearch:elasticsearch
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/rentit?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
    rentit-mysql:
        extends:
            file: mysql.yml
            service: rentit-mysql
    rentit-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: rentit-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
